name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: v2-rewrite

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies & PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "irn-windows" main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: irn-windows-exe
          path: dist/irn-windows.exe
